{% set version = "1.7.1" %}

package:
  name: pytorch-base
  version: {{ version }}

source:
  git_url: https://github.com/pytorch/pytorch.git
  git_rev: v{{ version }}
  patches:
    # 01xx - patch is specific to open-ce and will always be carried forward and not upstreamed
    - 0100-set-cmake_minimum_required-to-3.14.patch
    - 0101-shared-linker.patch
    - 0102-pytorch-tensorrt-Fix-for-GLIBC_2.14.patch # [x86_64 and py<38]
    - 0103-eigen-quiet-build-warning-for-missing-return.patch
    - 0104-onnx-tensorrt-TRT7.patch                  # [py<38]

    # 03xx - patch temporary to fix a problem that when fixed upstream can be removed
    - 0301-PR37865-Fix-compile-errors-related-to-disabling-xnnpack.patch
    - 0302-cpp-extension.patch
    - 0303-PR47677-remove-references-to-typing-module.patch

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libgcc-ng
    - {{ compiler('fortran') }}
    - git >={{ git }}

  host:
    - make
    - cmake {{ cmake }}
    - python {{ python }}
    - numpy {{ numpy }}
    - dataclasses {{ dataclasses }}          # [py36]
    - setuptools {{ setuptools }}
    - pyyaml {{ pyyaml }}
    - cffi {{ cffi }}
    - protobuf {{ protobuf }}
    - onnx {{ onnx }}
    - future {{ future }}
    - openblas-devel {{ openblas }}
    - numactl {{ numactl }}
    - lmdb {{ lmdb }}
    - leveldb {{ leveldb }}
    - libgfortran-ng {{ libgfortran }}
{% if build_type == 'cuda' %}
    - cudnn {{ cudnn }}
    - nccl {{ nccl }}
    - magma {{ magma }}
    - tensorrt {{ tensorrt }}                #[py<38]
{% endif %}

  run:
    - python {{ python }}
    - numpy {{ numpy }}
    - cffi {{ cffi }}
    - protobuf {{ protobuf }}
    - tabulate {{ tabulate }}
    - onnx {{ onnx }}
    - future {{ future }}
    - pillow {{ pillow }}
    - ninja {{ ninja }}
    - typing_extensions {{ typing_extensions }}  #[py<38]
    - click {{ click }}
    - networkx {{ networkx }}
    - scikit-image {{ scikit_image }}
    - scipy {{ scipy }}
    - numactl {{ numactl }}
    - numba {{ numba }}
    - lmdb                        # versioning handled by run_exports
    - leveldb                     # versioning handled by run_exports
    - python-lmdb {{ python_lmdb }}
    - pyyaml {{ pyyaml }}
    - absl-py {{ absl_py }}
    - libgfortran-ng              # versioning handled by run_exports
    - _pytorch_select {{ pytorch_select_version }}
{% if build_type == 'cuda' %}
    - cudatoolkit {{ cudatoolkit }}
    - cudnn {{ cudnn }}
    - nccl {{ nccl }}
    - tensorrt {{ tensorrt }}                    #[py<38]
{% endif %}

  run_constrained:
    - tensorboard {{ tensorboard }}

build:
  number: 6
{% if build_type == 'cpu' %}
  string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}
{% else %}
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}
{% endif %}
  detect_binary_files_with_prefix: False
  script_env:
    - CUDA_HOME

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
  description: |
    PyTorch is an optimized tensor library for deep learning using GPUs and CPUs

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
