package:
  name: _pytorch_select
  version: {{ pytorch_select_version }}

build:
  number: 1
{% if build_type == 'cpu' %}
  string: {{ build_type }}_{{ PKG_BUILDNUM }}
{% else %}
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_{{ PKG_BUILDNUM }}
{% endif %}

about:
  summary : Package used to select the specific PyTorch build variant

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
