package:
  name: _pytorch_select
  version: {{ pytorch_select_version }}

build:
  number: 2
  string: {{ build_type }}_{{ PKG_BUILDNUM }}

about:
  summary : Package used to select the specific PyTorch build variant

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
